### ISSUE TITLE
CFW CFP forms links

### ISSUE THREAD

**Issue by TopazA** [klepas/ozlockcon.com#25]
Please add these links for the CFP and CFW 

https://docs.google.com/forms/d/e/1FAIpQLScnTJSsOE7BQQhB9h-7vX8-ZSq3yEYInoZ1oaCx449BjGocjQ/viewform

https://docs.google.com/forms/d/e/1FAIpQLSek7UopUnAegE6837dtcE-PcPeQDq_yUSOFvc7DE_nArDE0Vw/viewform

**Comment by barnie995** [comment]
Awaiting PR #29
