### ISSUE TITLE
Add HHH section to FAQ

### ISSUE THREAD

**Issue by klepas** [klepas/ozlockcon.com#49]
> OzLockCon is stepping up to help other hackers in need. Currently, the organisation "Hackers Helping Hackers" is stuck in legal-limbo sorting paperwork to allow them to continue to do their excellent work. In the meantime, they've advised that we accept applications direct. As a result, this application is a slimmed down and slightly modified version of the one you'd need to submit for HHH.
> 
> Applicants will be notified at least one month prior to the conference as to the success of their submission, sooner if logistics allow. 
> 
> If you have any questions, please feel free to email directly to admin@ozlockcon.com 
> 
> Otherwise, feel free to submit a [Hackers Helping Hackers application](https://docs.google.com/forms/d/1YzfjMOSIwRfWDwsnS8s3tP6ZzFFip3HrksgYfAS10rQ/).

Reword/simplify.

**Comment by barnie995** [comment]
Done and on the live server. May need improvement however
