### ISSUE TITLE
Ribbon bar

### ISSUE THREAD

**Issue by TopazA** [klepas/ozlockcon.com#6]
Please Have in this order:

Call for papers & Workshops | Schedule | Venue || Code of Conduct | FAQ | Contact | Sponsors

Can have an extra wide break between venue and CoC

Please remove @ozlockcon twitter handle from ribbon and include include Twitter link at bottom of page

**Comment by barnie995** [comment]
Done.  

Ive put the twitter link at the bottom but its not 100% working right.  It seems to be getting it as a page on my local copy and not registering it as an actual page.  Dunno why at all

**Comment by klepas** [comment]
Gonna make the style refinements to the navbar in order to support #5 in a branch just of that.
