### ISSUE TITLE
Whats this? Content Change

### ISSUE THREAD

**Issue by TopazA** [klepas/ozlockcon.com#7]
OzLockCon aims to be the first open and inclusive community event focusing on physical security controls in Australia. 

The conference aims to introduce people from all areas of security, whether professionals or hobbyists, to new techniques, tools and ideas in order to learn new skills or refine existing ones.

We hope to have both standard talks and a variety of on-going workshops open to attendees with industry-leading presenters and tutors across a diverse range of topics.

Our aim is to cover not only traditional physical security controls (such as locks and safes) but more modern access control systems that are increasingly becoming more digital as time goes on. This will not only include network connected devices but also devices relying on radio communications in order to operate.

**Comment by barnie995** [comment]
Done.  PR incoming
