### ISSUE TITLE
New page - Sponsors

### ISSUE THREAD

**Issue by TopazA** [klepas/ozlockcon.com#9]
Please create a page with a format similar to this:

![image](https://cloud.githubusercontent.com/assets/10678727/22767385/fcd8507a-eece-11e6-947b-3489ac7a8b0a.png)

For the time-being, while we have no sponsors, just have the text under a heading:
"Interested in being a sponsor?"
Then include filler text for the time being while we write the request for sponsors.

**Comment by barnie995** [comment]
Done.  Went through the draft Ozmart gave me and put it up

**Comment by klepas** [comment]
@TopazA done. Feel free to edit sponsors.md to your heart’s content. ^_^
